### ISSUE TITLE
code

### ISSUE THREAD

**Issue by docShen** [Pbihao/HDMNet#1]
Hello, we are very interested in your work. May I ask when the training and testing code can be released? Thanks!

**Comment by Pbihao** [comment]
Yes, of course!

But bow the codes are a little bit messy. I will reorganize them later since I have been a little busy recently.

If you are in a hurry. I can send the raw projects with our models through email first.

Thanks for your interest and welcome for further discussion.

**Comment by Superwen1017** [comment]
Could you send me the raw projects, thank you！my email is 1027335035@qq.com

**Comment by wwei247** [comment]
Thank you , I am very interested in your work, my email is 14868677@qq.com

**Comment by Holmes-GU** [comment]
Could you send me the raw projects, thank you！Email address: gzhmsy@126.com

**Comment by kkang-ai** [comment]
I am very interested in your work. Could you send me the raw projects, thank you！my email is 1453406674@qq.com

**Comment by RIA1159** [comment]
This is an excellent work! Could you send me the raw projects, my email is trirawchan@gmail.com

**Comment by vangjin** [comment]
I am very interested in the great work, could you send me the raw projects, thank you. Email: wangjin035@163.com

**Comment by maxhang4339** [comment]
I am very interested in your excellent work and want to know more details about it, could you send me the raw projects to my email : 499317774@qq.com 
Thank you!

**Comment by Pbihao** [comment]
Thanks for your interest in our work!

We have received many requests.

The raw code is directly released. Our model will be updated soon.
