### ISSUE TITLE
Training logs and model weights.

### ISSUE THREAD

**Issue by zhuolingli** [Pbihao/HDMNet#10]
Hi, I'm very interested in your work.
Would it be convenient for you to share the model weights or training logs on Pascal dataset?

**Comment by Pbihao** [comment]
Hi! We science thank you for your interest in our work.

We highly recommend you reproduce the experiments on the Pascal dataset by yourself and mainly refer to the COCO dataset results. The results of Pascal are instability and more discussions can be found in the supplement materials.

However, we have uploaded the log information with the results reported in the main-paper: 
https://mycuhk-my.sharepoint.com/:f:/g/personal/1155186045_link_cuhk_edu_hk/EpUf0dvw9apAoS9wCBVnJ0sBzNs6L18UBjNHh5n1makkrA?e=vJaFOb

We take the experiment once, and maybe you can get higher by reproducing multi times.

**Comment by zhuolingli** [comment]
Thanks for your reply, which has been really helpful to me.
