### ISSUE TITLE
实现细节

### ISSUE THREAD

**Issue by Nastu-Ho** [Pbihao/HDMNet#16]
![image](https://github.com/Pbihao/HDMNet/assets/39642013/d47c2f68-a3f3-4f53-a8ef-86c4d3340d93)
作者您好，我发现correlation module实现视乎与论文中的表达不太一致。
在论文中的描述，correlation module的输入应该是 query_feat 和 用supp_mask 处理过的supp_feat。
但在您的代码实现中并没有这一步，而是对attn matrix用supp_mask 处理。
![image](https://github.com/Pbihao/HDMNet/assets/39642013/375f0f19-5e68-4480-8afd-b11e97ecd16c)
请问是为什么呢？还是我没找着。

还有一个小问题：就是之前的工作似乎都摒弃了在输入的时候就用mask处理supp_samples，转而对supp_feat用mask处理。您的方法又重新采纳回这种方案，请问是为什么呢？有没有相关的对比实验数据？

**Comment by Pbihao** [comment]
您好，首先感谢您对于我们工作的兴趣。
这里其实最终的效果是一样的，都是消除非mask部分的影响，只是代码的写法不同，这里是在attention的部分mask，是我的代码习惯。
对于第二个问题，首先感谢您提出这个问题，这个问题很有趣。
在我们的实验过程中，我们发现在输入的时候就使用mask处理，相比于之前的工作，会导致模型在coco数据集上表现出更好的效果吗，但是在pascal上导致效果变差。可以在coco上有一个多点的提升，在Pascal上也有一个点左右的下降，具体的数值没有找到抱歉。
当时我们分析这种情况出现的原因是由于Pascal数据集中的图片过于干净，一个图片中往往只有一两个类别，所以few-shot的分割会退化为前景分割，这一部分的讨论可以参考我们的补充材料。
而在COCO数据集中，由于类别过多，在feature部分才使用mask可能会导致不同类别之间产生干扰。
而我们觉得，COCO数据集更加贴合现实，因为自然场景很难出现像Pascal那样干净的图片，因此最终选用了第二种方法，尽管这使得我们的方法与之前的模型在Pascal上的表现更难拉开差距，这一部分可参考我们的补充材料。
祝您科研顺利！

**Comment by Nastu-Ho** [comment]
很感谢您这么快速地解答了我的疑惑。
还有另外一个问题想请教一下：
您有测过像HS-Net那样，在基于训练好的1-shot model下，去测5-shot setting的表现？有的话可以提供相关的数据吗？
我觉得5-shot setting又重新训一个模型太耗时间了(T⌓T)，而且我觉得HS-Net的策略更灵活一点（说到底还是卡不够多(T⌓T）)。

**Comment by Pbihao** [comment]
抱歉啊，这个实验我还真没有做个。few-shot确实挺吃卡的，我的coco实验用了16张3090跑了四天 (T_T....)
不过应该也不会有reviewer专门要求进行这个实验，放心啦！
祝您科研顺利
