### ISSUE TITLE
Pascal复现差异大

### ISSUE THREAD

**Issue by Codeganef** [Pbihao/HDMNet#17]
您好，感谢您的出色工作
对Pascal数据集复现结果时，出现与论文较大的差异，想问下是什么原因呢

**Comment by Pbihao** [comment]
您好，首先感谢您对于我们工作的兴趣。
不过老实说，这种提问方式约等于啥都没问吧，可能性太多了吧，环境，配置，数据，bug等等。
不过已经有很多同学包括我们自己都是复现成功的了的，麻烦您可以仔细检查一下。
祝你科研顺利

**Comment by Pbihao** [comment]
另外，按照我们的经验，Pascal应该是所有的方法基本差距都不大的，因为基本已经到达了一个理论准确度的上限（即去掉小样本的限制），这和Pascal数据集有关，Pascal的数据比较简单。
一点经验分享，希望能帮到。

**Comment by Codeganef** [comment]
感谢您的回复，我在猜想是否是我的pascal数据集构建有问题，我所构建的Pascal数据集使用了SegmentationClassAug来替换SegmentationClass，一共有12031张gt，这样构建是否正确呢？

**Comment by Pbihao** [comment]
我建议直接参考PFENet的做法，我们后面的工作都是参考他的

**Comment by qjmltz** [comment]
> 感谢您的回复，我在猜想是否是我的pascal数据集构建有问题，我所构建的Pascal数据集使用了SegmentationClassAug来替换SegmentationClass，一共有12031张gt，这样构建是否正确呢？

您好，我在复现Pascal的时候也出现了差异大的情况，也是使用SegmentationClassAug数据集，所有设置lists和initmodel都是基于BAM项目，不知道您后面是怎么处理的？

**Comment by Codeganef** [comment]
我多次复现之后也没有成功，不知道什么原因，至今没有解决

--------------原始邮件--------------
发件人："qjmltz ***@***.***&gt;;
发送时间：2024年5月27日(星期一) 晚上10:18
收件人："Pbihao/HDMNet" ***@***.***&gt;;
抄送："吕健图 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [Pbihao/HDMNet] Pascal复现差异大 (Issue #17)
-----------------------------------

 

  
感谢您的回复，我在猜想是否是我的pascal数据集构建有问题，我所构建的Pascal数据集使用了SegmentationClassAug来替换SegmentationClass，一共有12031张gt，这样构建是否正确呢？
  
您好，我在复现Pascal的时候也出现了差异大的情况，也是使用SegmentationClassAug数据集，所有设置lists和initmodel都是基于BAM项目，不知道您后面是怎么处理的？

**Comment by JiaojiaoYe1994** [comment]
这是我在Pascal-5i split0上的复现结果，请教大家这个要怎么看呢，最终的mIoU是看哪个值？

![image](https://github.com/Pbihao/HDMNet/assets/38762818/3659dd66-6da4-40e8-bf13-ef69cfcbecff)
