### ISSUE TITLE
关于训练时间

### ISSUE THREAD

**Issue by shiyi0306** [Pbihao/HDMNet#4]
您好，不知道您对实验的整个训练时间是否有过统计，方便透露下各个实验的训练时长吗？

**Comment by Pbihao** [comment]
您好，感谢您对我们工作的兴趣！
我的训练情况是这样的：
四卡 Nvidia GeForce RTX 3090 训练， 单卡推理
Pascal - 1shot - Resnet50：Total running time: 07h 33m 30s
Pascal - 5shot - Resnet50：Total running time: 18h 49m 39s
Pascal - 1shot - VGG： Total running time: 08h 19m 58s
Pascal - 5shot - VGG： Total running time: 08h 42m 10s
COCO- 1shot - Resnet50：Total running time: 27h 22m 37s
COCO- 5shot - Resnet50：Total running time: 88h 48m 53s
COCO- 1shot - VGG： Total running time: 12h 21m 26s
COCO- 5shot - VGG： Total running time: 27h 27m 38s
