### ISSUE TITLE
"align_corners" in resize function

### ISSUE THREAD

**Issue by zhuolingli** [Pbihao/HDMNet#9]
感谢您极好的工作！
想请教您，在代码中您交替使用了mmseg的resize和F.interpolate来进行双线性插值。但在mmseg的resize函数中，align_conners参数设置为false，而其在F.interpolate中设置为True。请问这有具体的缘由吗？

**Comment by Pbihao** [comment]
感谢您的兴趣。

按照经验这种细节应该影响不会太大，可能就是写代码的时候习惯问题。

设置为True的话会消耗一点计算资源但是这种low-level的对齐一般对于整个实验的影响有限。

当然有兴趣的话你也可以验证一下。

祝您实验顺利！
